<h1><span style="color:blue">Busca y descarga el conjunto de datos “Optical Recognition of
Handwritten Digits” del repositorio UCI Machine Learning. Tiene los
datos de un problema de clasificación multiclase. Cárgalo
adecuadamente en un Pandas DataFrame. El data set viene
segmentado en datos de entrenamiento y validación (optdigits.tra y
optdigits.tes, respectivamente).
  </span></h1>

In [1]:
from pandas import read_csv 
from sklearn.neural_network import MLPClassifier 
import time, random 
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, accuracy_score, balanced_accuracy_score 

import matplotlib.pyplot as plt

seed=random.seed(time.time())

Para mayor facilidad le cambié el nombre a los datasets: train.csv, test.csv

También encontré el nombre de la columnas buscando en los datasets de SKLearn. Utilicé el dataset solo para mirar los nombre de las columnas.

In [2]:
filename = 'train.csv'  
col_names=['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'output'] 
df = read_csv(filename, names=col_names)  

df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,output
0,1,6,15,12,1,0,0,0,7,16,...,0,0,0,6,14,7,1,0,0,0
0,0,10,16,6,0,0,0,0,7,16,...,0,0,0,10,16,15,3,0,0,0
0,0,8,15,16,13,0,0,0,1,11,...,0,0,0,9,14,0,0,0,0,7
0,0,0,3,11,16,0,0,0,0,5,...,0,0,0,0,1,15,2,0,0,4
0,0,5,14,4,0,0,0,0,0,13,...,0,0,0,4,12,14,7,0,0,6

In [3]:
class_distribution = df.groupby('output').size()
print(class_distribution)

output
0    376
1    389
2    380
3    389
4    387
5    376
6    377
7    387
8    380
9    382
dtype: int64

In [4]:
filename = 'test.csv'  
col_names=['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'output'] 
df1 = read_csv(filename, names=col_names)  

df1.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,output
0,0,5,13,9,1,0,0,0,0,13,...,0,0,0,6,13,10,0,0,0,0
0,0,0,12,13,5,0,0,0,0,0,...,0,0,0,0,11,16,10,0,0,1
0,0,0,4,15,12,0,0,0,0,3,...,0,0,0,0,3,11,16,9,0,2
0,0,7,15,13,1,0,0,0,8,13,...,0,0,0,7,13,13,9,0,0,3
0,0,0,1,11,0,0,0,0,0,0,...,0,0,0,0,2,16,4,0,0,4

<h1><span style="color:blue"> Realiza el preprocesamiento más adecuado para los datos. </span></h1>

#### Primero

Divido los datos entre los inputs y el output.

Como este data set ya vienen dividido no tengo que dividir la parte de test sino que importo el dataset de test.

Cada linea representa los bits de una imagen

Al final se trata de comparar si coniscide con el numero de **OUTPUT**

Los numeros van de 0-9

In [5]:
X_train = df[df.columns[:-1]] 

X_test = df1[df.columns[:-1]] 

y_train = df['output'] 

y_test = df1['output']

<h3><span style="color:red">Escalado de datos</span></h3>

Separar las variables que sean de tipo numerico de las categoricas.
Y con **EstandardScaler** le aplico un escaldo a esas variables numericas.

#### **NUMERICAS** ---------------> StandardScaler

In [6]:
scaler =StandardScaler()
X_train = scaler.fit_transform(X_train) 

X_test= scaler.transform(X_test)

<h1><span style="color:blue"> Entrena un modelo de redes neuronales para clasificación y evalúa su
rendimiento.
 </span></h1>

In [7]:
model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, activation='logistic', n_iter_no_change=50, solver='lbfgs').fit(X_train, y_train)

Ahora tomamos los datos de test y los comparamos con el modelo ya entrenado

In [8]:
y_pred = model.predict(X_test)

In [9]:
bacc =  balanced_accuracy_score(y_pred, y_test) 

acc =  accuracy_score(y_pred, y_test) 
cm =  confusion_matrix(y_pred, y_test)  

print(bacc, acc) 

print(cm)

0.9568579491785295 0.9560378408458542
[[175   0   0   0   0   0   1   1   0   0]
 [  0 179   6   0   1   0   0   0   8   0]
 [  0   0 171   5   0   0   0   0   0   0]
 [  0   0   0 173   0   1   0   0   3   1]
 [  0   0   0   0 176   0   1   1   2   1]
 [  2   0   0   2   0 177   0   6   1   4]
 [  0   2   0   0   0   1 179   0   1   0]
 [  0   0   0   0   0   1   0 164   0   0]
 [  1   1   0   1   3   1   0   1 153   3]
 [  0   0   0   2   1   1   0   6   6 171]]

<h1><span style="color:blue"> Trata de buscar la mejor combinación para los distintos parámetros
del modelo </span></h1>

Creo otro dataframe para almacenar la infomación de rendimiento.

In [10]:
import pandas as pd

cols = ['Función de activación','Layers ocultos','Algoritmo de optimización', 'Accuracy','Balanced accuracy']

df_2 = pd.DataFrame(columns=cols)


activation = ['identity', 'logistic', 'relu','tanh']

hiddenLayers = [10,50,100,200]

solver = ['lbfgs','sgd','adam']


for a in activation:
    for b in hiddenLayers:
        for c in solver: 
            
            model = MLPClassifier(hidden_layer_sizes=(b,), max_iter=1000, activation= a, n_iter_no_change=50, solver= c).fit(X_train, y_train)
            y_pred = model.predict(X_test)
            
            bacc =  balanced_accuracy_score(y_pred, y_test) 

            acc =  accuracy_score(y_pred, y_test) 
            cm =  confusion_matrix(y_pred, y_test)
            
            
            new_row = {'Función de activación':a, 'Algoritmo de optimización':c, 'Layers ocultos':b, 'Accuracy':acc, 'Balanced accuracy':bacc}
            df_2 = df_2.append(new_row, ignore_index=True) 

df_2

C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
c:\users\mauro.cespedesaraya\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)

C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)
C:\Users\Mauro.CespedesAraya\AppData\Local\Temp\ipykernel_17152\4218199160.py:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_2 = df_2.append(new_row, ignore_index=True)

,Función de activación,Layers ocultos,Algoritmo de optimización,Accuracy,Balanced accuracy
0,identity,10,lbfgs,0.936004,0.937371
1,identity,10,sgd,0.949917,0.951034
2,identity,10,adam,0.941013,0.942406
3,identity,50,lbfgs,0.939343,0.940236
4,identity,50,sgd,0.947134,0.948784
5,identity,50,adam,0.938230,0.939492
6,identity,100,lbfgs,0.939343,0.940313
7,identity,100,sgd,0.947134,0.948317
8,identity,100,adam,0.937674,0.939031
9,identity,200,lbfgs,0.942126,0.943562
10,identity,200,sgd,0.947134,0.948494
11,identity,200,adam,0.938787,0.939919
12,logistic,10,lbfgs,0.925431,0.925979
13,logistic,10,sgd,0.934891,0.936682
14,logistic,10,adam,0.938787,0.939307
15,logistic,50,lbfgs,0.955481,0.956328
16,logistic,50,sgd,0.951029,0.952440
17,logistic,50,adam,0.962716,0.963552
18,logistic,100,lbfgs,0.957707,0.958714
19,logistic,100,sgd,0.948804,0.950030
20,logistic,100,adam,0.967724,0.968745
21,logistic,200,lbfgs,0.964942,0.966544
22,logistic,200,sgd,0.948804,0.950102
23,logistic,200,adam,0.966611,0.967528
24,relu,10,lbfgs,0.941013,0.942030
25,relu,10,sgd,0.947134,0.947932
26,relu,10,adam,0.948247,0.949653
27,relu,50,lbfgs,0.962159,0.963916
28,relu,50,sgd,0.958264,0.959482
29,relu,50,adam,0.967168,0.968128
30,relu,100,lbfgs,0.964385,0.965339
31,relu,100,sgd,0.963272,0.964097
32,relu,100,adam,0.971063,0.971488
33,relu,200,lbfgs,0.963272,0.964124
34,relu,200,sgd,0.961603,0.962589
35,relu,200,adam,0.969393,0.969929
36,tanh,10,lbfgs,0.911519,0.914143
37,tanh,10,sgd,0.943239,0.944092
38,tanh,10,adam,0.939343,0.939917
39,tanh,50,lbfgs,0.962159,0.962804
40,tanh,50,sgd,0.954925,0.955791
41,tanh,50,adam,0.960490,0.961344
42,tanh,100,lbfgs,0.961046,0.962202
43,tanh,100,sgd,0.956038,0.957058
44,tanh,100,adam,0.963829,0.964478
45,tanh,200,lbfgs,0.961046,0.962004
46,tanh,200,sgd,0.954925,0.956313
47,tanh,200,adam,0.965498,0.966126

Ahora lo que quiero es encontrar a partir de este nuevo dataset la combinacion que mejor y pero funciona, através de un FOR loop.

In [11]:
for i in df_2.index:
    if (df_2['Accuracy'][i] == df_2['Accuracy'].max()) and (df_2['Balanced accuracy'][i] == df_2['Balanced accuracy'].max()): 

        print('La combinación que MEJOR funciona es :')
        print(df_2.iloc[[i]])
        print('---------------------------------------')
        
    else:
        pass
    
    if (df_2['Accuracy'][i] == df_2['Accuracy'].min()) and (df_2['Balanced accuracy'][i] == df_2['Balanced accuracy'].min()):
        
        print('La combinación que PEOR funciona es :')
        print(df_2.iloc[[i]])
        print('---------------------------------------')
        
    else:
        pass

La combinación que MEJOR funciona es :
   Función de activación Layers ocultos Algoritmo de optimización  Accuracy  \
32                  relu            100                      adam  0.971063

    Balanced accuracy
32           0.971488
---------------------------------------
La combinación que PEOR funciona es :
   Función de activación Layers ocultos Algoritmo de optimización  Accuracy  \
36                  tanh             10                     lbfgs  0.911519

    Balanced accuracy
36           0.914143
---------------------------------------